# commit to be tagged for new release
commit = "HEAD"

project_name = "moby"
github_repo = "moby/moby"
sub_path = "client"
ignore_deps = [ "github.com/moby/moby" ]

# previous release
previous = "v28.3.3"

pre_release = true

preface = """\
The first dedicated release for the Moby client.
"""